name: SSH Canary
on:
  workflow_dispatch: {}
  push:
    branches: ["main"]

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: "Write SSH key"
        run: |
          echo "${{ secrets.DEPLOYER_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: "SSH test"
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=accept-new \
            deployer@${{ secrets.DROPLET_IP }} "whoami && hostname"
