name: Deploy FastAPI to Droplet

on:
  push:
    branches: ["master"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Write SSH key from base64"
        run: |
          echo "${{ secrets.DEPLOYER_SSH_KEY }}" | base64 -d > key.pem
          sed -i 's/\r$//' key.pem || true
          chmod 600 key.pem
          # Quick sanity:
          head -n1 key.pem; tail -n1 key.pem

      - name: "Verify repo structure"
        run: |
          test -f requirements.txt
          test -f app/main.py

      - name: "Sync code to server"
        run: |
          rsync -avzr --delete --exclude='.git' --exclude='.github' \
            -e "ssh -i key.pem -o StrictHostKeyChecking=accept-new" \
            ./ deployer@${{ secrets.DROPLET_IP }}:/var/www/fastapi-app-totext

      - name: "Install deps & restart service"
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=accept-new \
            deployer@${{ secrets.DROPLET_IP }} <<'SSH'
            set -euo pipefail

            # Pick a Python available on server
            PY_BIN="$(command -v python3.11 || command -v python3.10 || command -v python3)"
            echo "Using: $PY_BIN"

            # Create venv if missing
            if [ ! -d "/home/deployer/venvs/fastapi-app-totext" ]; then
              "$PY_BIN" -m venv /home/deployer/venvs/fastapi-app-totext
            fi

            # Install/upgrade dependencies
            /home/deployer/venvs/fastapi-app-totext/bin/pip install --upgrade pip wheel
            /home/deployer/venvs/fastapi-app-totext/bin/pip install -r /var/www/fastapi-app-totext/requirements.txt

            # (Optional) run DB migrations here
            # /home/deployer/venvs/fastapi-app-totext/bin/alembic upgrade head || true

            # Reload service files + restart app
            sudo systemctl daemon-reload
            sudo systemctl restart fastapi-app-totext

            # Show brief status (won’t fail pipeline)
            sudo systemctl status fastapi-app-totext --no-pager || true
          SSH
